services:
  api:
    build:
      context: .
      dockerfile: server/Todo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Data Source=todo.db"
    ports:
      - "5001:80"
    volumes:
      - todo_data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/graphql || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  todo_data:
