services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - todo_db_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ../
      dockerfile: server/Todo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db;Database=TodoDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/graphql || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build:
      context: ../
      dockerfile: web/client/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:80"

volumes:
  todo_db_data:
